# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI for managing Kurtosis environments."
  homepage "https://www.kurtosistech.com"
  version "1.19.11"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.19.11/kurtosis-cli_1.19.11_darwin_amd64.tar.gz"
      sha256 "62e93ea24c3d2fce6d9ab67284604472691ed86670a2eda9fb6ba76a25a3be62"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.19.11/kurtosis-cli_1.19.11_darwin_arm64.tar.gz"
      sha256 "f16da8d8cfd2e5be77c3ec7803ef3922a94e670ed25fcda863d7f25127a0f36a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.19.11/kurtosis-cli_1.19.11_linux_amd64.tar.gz"
      sha256 "f1d12238c91fd20534029cd065d47b6c409292805d7d426c9ecf0392ef9b80f8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.19.11/kurtosis-cli_1.19.11_linux_arm64.tar.gz"
      sha256 "cca5a1dfb76a31686f058c3b8d0b3917e74f4a20374d9b66b0587f884c6c4fea"
    end
  end

  def install
    bin.install "kurtosis"
  end
end
