# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kurtosis < Formula
  desc "CLI for managing Kurtosis environments."
  homepage "https://www.kurtosistech.com"
  version "1.22.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.22.1/kurtosis-cli_1.22.1_darwin_amd64.tar.gz"
      sha256 "91adf1e8aff069b7e578d595dd6a3cf620a333af327e2d6a1f97bc9561bfa9bd"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.22.1/kurtosis-cli_1.22.1_darwin_arm64.tar.gz"
      sha256 "e4428096493d4b0a21eac20bdac25ecc2c8e5a8588429963c914641f094cf770"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.22.1/kurtosis-cli_1.22.1_linux_amd64.tar.gz"
      sha256 "465e38cbccdf46f350c97515df4e82a300c04f9975b58abbea89a1d2041dd074"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.22.1/kurtosis-cli_1.22.1_linux_arm64.tar.gz"
      sha256 "c49d19b88942317aec01076ce8811924c669d4d4502e528788176152e218d19b"
    end
  end

  def install
    bin.install "kurtosis"
  end
end
