# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KurtosisCli < Formula
  desc "CLI for managing Kurtosis environments."
  homepage "https://www.kurtosistech.com"
  version "0.53.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/v0.53.0/kurtosis-cli_0.53.0_darwin_arm64.tar.gz"
      sha256 "2da76549ed464354506487194b89422edb5cb9b933e4f12af155185d68f77f9d"

      def install
        bin.install "kurtosis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/v0.53.0/kurtosis-cli_0.53.0_darwin_amd64.tar.gz"
      sha256 "f3dbd7e080640fad164bb609520f2cb9dfc84ee829b814d83aee181df8fdf6fb"

      def install
        bin.install "kurtosis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/v0.53.0/kurtosis-cli_0.53.0_linux_arm64.tar.gz"
      sha256 "1fbcf1511846bacb6165467b5923f66b75b6a8146de55fd8c1c9833cc8601999"

      def install
        bin.install "kurtosis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/v0.53.0/kurtosis-cli_0.53.0_linux_amd64.tar.gz"
      sha256 "b1da64e1aa7ff5f22ab678232cde90461832ee98591092e9edef2f9f8f5ac118"

      def install
        bin.install "kurtosis"
      end
    end
  end
end
