# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kurtosis < Formula
  desc "CLI for managing Kurtosis environments."
  homepage "https://www.kurtosistech.com"
  version "1.20.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.20.1/kurtosis-cli_1.20.1_darwin_amd64.tar.gz"
      sha256 "aceedabfa8fd57a7f9331792d8e329ef0f192054dd3b2dd6d574420d4d88e1b1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.20.1/kurtosis-cli_1.20.1_darwin_arm64.tar.gz"
      sha256 "8a06c4f4687bd87dce0d26c5cd6b1e7cb2721ad222b5cd617db80e1efc2b8718"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.20.1/kurtosis-cli_1.20.1_linux_amd64.tar.gz"
      sha256 "62e4a2f917c5412bf5e6764c6fcbaa48911863f261e0e7a152984aec9b4fd651"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurtosis-tech/kurtosis-core-release-artifacts/releases/download/1.20.1/kurtosis-cli_1.20.1_linux_arm64.tar.gz"
      sha256 "24ff5e36c1bde86213e36ade91e24cc4734c3f619a2d59a5d68fa52b69e2b2b3"
    end
  end

  def install
    bin.install "kurtosis"
  end
end
