# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KurtosisCli < Formula
  desc "CLI for managing Kurtosis environments."
  homepage "https://www.kurtosistech.com"
  version "0.57.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/v0.57.3/kurtosis-cli_0.57.3_darwin_arm64.tar.gz"
      sha256 "e32d8ae67fb5e2ebab8504a88b49b20ff3d3171c83b42fe2c6ab7ae50ff7a1d1"

      def install
        bin.install "kurtosis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/v0.57.3/kurtosis-cli_0.57.3_darwin_amd64.tar.gz"
      sha256 "e071a0d8a90b877be743342da24db92ad8c0ff66305f409e692a564b9419a27b"

      def install
        bin.install "kurtosis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/v0.57.3/kurtosis-cli_0.57.3_linux_arm64.tar.gz"
      sha256 "3c839ad77f2787d1ef7b38ad4d299a4e3393a6ce59b0ed3d43822f6f7178d7b2"

      def install
        bin.install "kurtosis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/v0.57.3/kurtosis-cli_0.57.3_linux_amd64.tar.gz"
      sha256 "52e5dca7d3f60b03a0772ab4e00284bf0978ab32d5fdab780f480ea3e6255bd1"

      def install
        bin.install "kurtosis"
      end
    end
  end
end
